### ISSUE TITLE
docker-ce的帮助文档中，换用镜像本身的GPG公钥与仓库链接

### ISSUE THREAD

**Issue by Side514** [mirrorz-org/mirrorz-docs#19]
由于几乎无法正常访问download.docker.com，帮助文档中的安装命令会执行不成功。

镜像源中已包含了GPG文件和仓库文件，因此能否考虑将安装命令中出现的`download.docker.com`替换为`mirrors.tuna.tsinghua.edu.cn/docker-ce`？

涉及文件如下：
https://github.com/mirrorz-org/mirrorz-docs/blob/0a737473cff21fe7c00cd21d51c380ed9ea8bea0/docker-ce/debian.zh.md?plain=1#L22
https://github.com/mirrorz-org/mirrorz-docs/blob/0a737473cff21fe7c00cd21d51c380ed9ea8bea0/docker-ce/fedora.zh.md?plain=1#L24
https://github.com/mirrorz-org/mirrorz-docs/blob/0a737473cff21fe7c00cd21d51c380ed9ea8bea0/docker-ce/centos.zh.md?plain=1#L23

**Comment by taoky** [comment]
> 镜像源中已包含了GPG文件和仓库文件，因此能否考虑将安装命令中出现的`download.docker.com`替换为`mirrors.tuna.tsinghua.edu.cn/docker-ce`？

不可以。出于安全考虑，帮助文档的中所有获取公钥的部分均从原始站点获取，即使可能在某些网络环境下不可用。

**Comment by taoky** [comment]
YUM/DNF 的 repo 文件可能可以切换到由镜像站提供（因为是原样从上游获取的）。
