### ISSUE TITLE
请求更改 pypi 镜像源使用帮助中 Poetry 设置默认镜像的方法

### ISSUE THREAD

**Issue by vagreargnatry** [mirrorz-org/mirrorz-docs#8]
[pypi 镜像源使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)

[Poetry 1.8.0](https://github.com/python-poetry/poetry/releases/tag/1.8.0) 不再建议使用 `--priority=default` 而是使用 `--priority=primary`

新的命令应该是这样 `poetry source add --priority=primary mirrors https://pypi.tuna.tsinghua.edu.cn/simple/`

**Comment by taoky** [comment]
如果可以的话交个 PR？

**Comment by TechCiel** [comment]
由于我只是维护文档系统，对 Poetry 不是非常熟悉，我参考了一下 [Poetry 的文档](https://python-poetry.org/docs/repositories/#package-sources) ，似乎 `default` (deprecated) 优先级完全由 `primary` 等价替代，但更早就已 deprecated 的 `secondary`  似乎也改用了新的 `supplemental` 优先级？

**Comment by vagreargnatry** [comment]
> 由于我只是维护文档系统，对 Poetry 不是非常熟悉，我参考了一下 [Poetry 的文档](https://python-poetry.org/docs/repositories/#package-sources) ，似乎 `default` (deprecated) 优先级完全由 `primary` 等价替代，但更早就已 deprecated 的 `secondary` 似乎也改用了新的 `supplemental` 优先级？

谢谢指正。我之前没有发现 `secondary` 也是 deprecated 的，现在才知道。

**Comment by TechCiel** [comment]
@vagreargnatry > > 由于我只是维护文档系统，对 Poetry 不是非常熟悉，我参考了一下 Poetry 的文档 ，似乎 default (deprecated) 优先级完全由 primary 等价替代，但更早就已 deprecated 的 secondary 似乎也改用了新的 supplemental 优先级？ 
 
> 谢谢指正。我之前没有发现 secondary 也是 deprecated 的，现在才知道。

我拿不准啊，我是在问你这样对不对劲（）

**Comment by vagreargnatry** [comment]
> @vagreargnatry > > 由于我只是维护文档系统，对 Poetry 不是非常熟悉，我参考了一下 Poetry 的文档 ，似乎 default (deprecated) 优先级完全由 primary 等价替代，但更早就已 deprecated 的 secondary 似乎也改用了新的 supplemental 优先级？
> 
> > 谢谢指正。我之前没有发现 secondary 也是 deprecated 的，现在才知道。
> 
> 我拿不准啊，我是在问你这样对不对劲（）

我觉得没有问题。我刚才用 `poetry source add --priority=secondary foo https://foo.bar/simple/` 试了一下，poetry (1.8.2) 告诉我 `Warning: Priority 'secondary' is deprecated. Consider changing the priority to one of the non-deprecated values: 'primary', 'supplemental', 'explicit'.` 现在这个版本的 poetry 应该使用的值我想就是 `primary`，`supplemental`，`explicit` 之一。
